// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Signup() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article style=\"width: 100%; max-width: 500px; margin: 0 auto;\"><hgroup><h1>Sign Up</h1><p>Create a new account</p></hgroup><form hx-post=\"/signup\" hx-swap=\"none\" hx-disabled-elt=\"find button\"><label for=\"username\" id=\"username-input\">Username <input id=\"username\" name=\"username\" required minlength=\"3\" maxlength=\"20\" type=\"text\" pattern=\"^[a-zA-Z0-9_]{3,20}$\" title=\"Only letters, numbers and underscores allowed\"> <small>Only letters, numbers and underscores allowed</small></label> <label for=\"email\" id=\"email-input\">Email <input id=\"email\" name=\"email\" required type=\"email\"></label> <label for=\"password\" id=\"password-input\">Password <input id=\"password\" minlength=\"8\" name=\"password\" required type=\"password\"> <small>Must be at least 8 characters long</small></label> <label for=\"confirm-password\" id=\"confirm-password-input\">Confirm Password <input id=\"confirm-password\" minlength=\"8\" name=\"confirm_password\" required type=\"password\"></label> <button type=\"submit\">Sign Up</button></form><p>Already have an account? <a href=\"/login\">Log in</a></p></article>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
